pp_security_login:
    pattern: /login
    defaults: { _controller: PropertyPrivatelySecurityBundle:Authentication:login }
    methods: [GET,POST]

pp_security_logout:
    pattern: /logout
    defaults: { _controller: PropertyPrivatelySecurityBundle:Authentication:logout }
    methods: [GET]
