parameters:
#    property_privately_security.example.class: PropertyPrivately\SecurityBundle\Example

services:
#    property_privately_security.example:
#        class: %property_privately_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
