parameters:
#    property_privately_showroom.example.class: PropertyPrivately\ShowroomBundle\Example

services:
#    property_privately_showroom.example:
#        class: %property_privately_showroom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
