property_privately_showroom:
    resource: "@PropertyPrivatelyShowroomBundle/Resources/config/routing.yml"
    prefix:   /

property_privately_security:
    resource: "@PropertyPrivatelySecurityBundle/Resources/config/routing.yml"
    prefix:   /

