security:
    access_decision_manager:
        strategy: unanimous

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default:
            id: pp_security.webservice_token_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login:
        #     pattern:  ^/login
        #     security: false

        secured_area:
            pattern:    ^/
            stateless: true
            simple_preauth:
                authenticator: pp_security.webservice_token_authenticator
            anonymous: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
